default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost  # when using localhost
  # host: db       # when using docker
  username: postgres
  password: postgres

development:
  <<: *default
  database: note_control_development

test:
  <<: *default
  database: note_control_test

production:
  primary: &primary_production
    <<: *default
    database: note_control_production
    username: note_control
    password: <%= ENV["NOTE_CONTROL_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: note_control_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: note_control_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: note_control_production_cable
    migrations_paths: db/cable_migrate
